# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^tools/

repos:

  # Standard hooks (yaml, eol, BOM, etc)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-json
      -   id: check-symlinks
      -   id: check-xml
      -   id: fix-byte-order-marker
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
      - id: forbid-tabs


  # Ruff: run the linter, but not the formatter (we use black)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      # - id: ruff-format


  # Run mypy static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      -   id: mypy

  # Black formatter: disabled by default, run manually
  #  - repo: https://github.com/psf/black
  #    rev: 23.12.1
  #    hooks:
  #      - id: black
  #        stages: [commit]
  #        # exclude_types: ["pyi"]


  # Run pytest: this works, but requires a venv to be set up at venv/
  # => disabled, since it is not recommended by pre-commit's team
  # See https://github.com/pre-commit/pre-commit/issues/761#issuecomment-394167542
  #  - repo: local
  #    hooks:
  #      - id: pytest-check
  #        name: pytest-check
  #        stages: [commit]
  #        types: [python]
  #        entry: venv/bin/pytest
  #        language: system
  #        pass_filenames: false
  #        always_run: true
