# type: ignore
import sys
from typing import Literal, List, Any, Optional, Tuple
import numpy as np
from enum import Enum
import numpy

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:examplelibcpp_amalgamation.h>    ####################
# THIS FILE WAS GENERATED AUTOMATICALLY. DO NOT EDIT.

#////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#                       examplelibcpp.h                                                                      //
#//////////////////////////////////////////////////////////////////////////////////////////////////////////////

#////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#                       examplelibcpp/examplelibcpp_2.h included by examplelibcpp.h                      //
#//////////////////////////////////////////////////////////////////////////////////////////////////////////////

def sub(a: int, b: int) -> int:
    pass


def add(a: int, b: int) -> int:
    """////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                           examplelibcpp.h continued                                                            //
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////
    """
    pass
####################    </generated_from:examplelibcpp_amalgamation.h>    ####################

# </litgen_stub>
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
