# type: ignore

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:examplelibcpp.h>    ####################

class Foo:
    a: int = 1
    s: str
    def __init__(self, a: int = 1, s: str = "") -> None:
        """Auto-generated default constructor with named params"""
        pass

def make_foo() -> Foo:
    pass


####################    </generated_from:examplelibcpp.h>    ####################

# </litgen_stub>
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
