#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>

#include "example_lib_cpp/example_lib_cpp.h"

namespace py = pybind11;


void py_init_module_example_lib(py::module& m)
{
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:example_lib_cpp_amalgamation.h>    ////////////////////
    m.def("sub",
        sub, py::arg("a"), py::arg("b"));

    m.def("add",
        add,
        py::arg("a"), py::arg("b"),
        "////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n                       example_lib_cpp.h continued                                                            //\n//////////////////////////////////////////////////////////////////////////////////////////////////////////////");
    ////////////////////    </generated_from:example_lib_cpp_amalgamation.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
