name: Wheels

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - published
  push:
    branches:
      - master
      - main

env:
  CIBW_TEST_COMMAND: pytest {project}/tests
  CIBW_TEST_EXTRAS: test
  CIBW_TEST_REQUIRES: pytest
  # skip testing pypy wheels on github CI (it works locally, but fails on github CI for a yet unknown reason)
  CIBW_TEST_SKIP: "pp3*"

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup interactive tmate session
      uses: mxschmitt/action-tmate@v3

    - uses: pypa/cibuildwheel@v2.16.2

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
